### PR TITLE
Fix issue with head content pushed into body

### PR DESCRIPTION
**Pull request by matthewp**
## Changes

- Since `resetInsertionMode` is used when expressions are ended there needs to be something on the `templateStack` for nested expressions. 
- There should be an `inExpressionIM` in the `templateStack`.
- Fixes https://github.com/withastro/compiler/issues/985
- Fixes https://github.com/withastro/compiler/issues/935

## Testing

- New printer test

## Docs

N/A, bug fix

### CODE REVIEW

**Comment by matthewp** [comment]
!preview head-body-content

**Comment by matthewp** [comment]
!preview head-body-content

**Comment by matthewp** [comment]
!preview head-body-content

**Comment by matthewp** [comment]
!preview head-body-content

**Review by deeprobin — APPROVED** [review]
LGTM

**Review by bluwy — APPROVED** [review]

**Pull request merged**
