### PR TITLE
Implement `Astro.self`

### PR DESCRIPTION
**Pull request by natemoo-re**
## Changes

- Implements the [Recursive Components RFC](https://github.com/withastro/rfcs/blob/main/active-rfcs/0000-recursive-components.md)
- Also implements better naming scheme for components, where the name will be generated from the file pathname if possible.

## Testing

WASM test added, `Astro.self` added to test output.

## Docs

Needs docs.

### CODE REVIEW

**Review by jonathantneal — APPROVED** [review]
I’m always confused by `opts.opts` but this looks good. L32 of printer_test.go tells me what I expect. :)

**Comment by natemoo-re** [comment]
Totally agree, @jonathantneal! Would be great to clean that up.

**Review by boehs — APPROVED** [review]
From a code quality standpoint this is spot on!

**Review by matthewp — APPROVED** [review]
lgtm

**Pull request merged**
