### PR TITLE
Improve JS Sourcemaps II

### PR DESCRIPTION
**Pull request by natemoo-re**
This reverts commit fd5cb5751e165f6137995fc62dc3ec7360b92558.

## Changes

- Closes https://github.com/withastro/compiler/issues/341
- See https://github.com/withastro/compiler/pull/674 which was rolled back in https://github.com/withastro/compiler/pull/678
- Preview release is passing on `main` via https://github.com/withastro/astro/pull/5656

## Testing

Need to add the failing condition

## Docs

N/A

### CODE REVIEW

**Comment by jasikpark** [comment]
what changed?

**Comment by natemoo-re** [comment]
Nothing yet! There was a failure here that I need to add a test case for https://github.com/withastro/astro/actions/runs/3744703887/jobs/6358389988

**Review by jasikpark — APPROVED** [review]
sounds good to me, this is just a remerge + checking in a failing integration test w/ astro

would really be great to set up astro-compiler-remote-ci to test compiler changes against astro proper

**Comment by jasikpark** [comment]
https://github.com/withastro/compiler/issues/341 👀 finally close this?

**Comment by natemoo-re** [comment]
!preview sourcemap

**Comment by natemoo-re** [comment]
Preview is passing on `main` here https://github.com/withastro/astro/pull/5656

**Pull request merged**
