### PR TITLE
Fix various issues with slots

### PR DESCRIPTION
**Pull request by MoustaphaDev**
## Changes

- Closes https://github.com/withastro/compiler/issues/724
- Closes https://github.com/withastro/compiler/issues/868
- Partially addresses https://github.com/withastro/astro/issues/8687, the `undefined` slot name issue will be tackled in another PR 
- Wrap the slot object around parens, otherwise, at runtime the leading curly brace would be parsed as an opening block statement [in some cases](https://live-astro-compiler.vercel.app/?editor-state=WzMxLDEzOSw4LDAsMjM5LDEzOSwxNjEsMTAxLDIsMywxMTcsODIsMjA1LDc0LDMsNDksMTYsMTI2LDE0OSwxNDQsMTQ3LDEzMywxMTgsNzUsMTk3LDgzLDEwNSwxMSwxNjUsMTYyLDgsMzAsMTY0LDkxLDEyNywxOTIsMTIwLDE1MiwxMTAsMTAyLDExNywzMywxNTUsMTMyLDczLDIxNCwxMzAsMTAxLDIyMywyMjEsMjAxLDE4MiwxNzQsMTk3LDIyNiw0NSwxNTMsMjM5LDEwMywxMDIsMTkwLDEwMCw0NywxMzksMTM0LDgsMTA5LDkyLDE4NSwyMTgsODcsNiwyMzMsOSw0MSw4NCwyMDYsMjAyLDE2OSwxODgsMjA0LDE3NCwxNzgsMTM3LDI4LDIwMiwxOTQsMTA1LDIyOCwyMzUsMTA0LDUyLDgyLDE4MiwxNzAsMTg5LDE2Myw0MCw1NCwyNCwxNjIsNDAsMjAxLDIxMyw2NiwyMDEsNDQsMjcsMjMsMTcyLDExNywxNTAsNzcsMTk0LDU2LDMzLDI1LDEzMiw3Miw3OCw3MywxMDEsMTQ5LDQ1LDE1NiwxMDEsMTcwLDEzNCw4LDk4LDQ2LDk0LDE0OSwyMSw5OCw0Nyw5NiwyMDIsMTc4LDI0OCw4MSw1LDM3LDEzNSw5OCwxNTUsNDYsMjMzLDQwLDIxOCwyMjUsOSwxMiw2MSwyMiwyMTcsMjQxLDEzNiwxOTAsNDEsMjE5LDc3LDE2MSwyMzYsNDQsMjQ1LDg5LDExNiwyNTIsMjI4LDE1NywyMTMsMjI0LDQ3LDQ2LDI0NCw2NCwyMDQsMjMsOTgsMjMwLDY5LDQ4LDQ2LDIwNiwxNDksMTU2LDQwLDE4NSwyMTYsMjM1LDEyLDIxOCwyMTcsMjE2LDI1NSw5MSwzMSwxODAsMjM2LDIxNCwxNDEsMjA1LDExOCwxODgsMjM3LDIwNiwxNDUsMTI2LDM4LDI0MCwzMCwxODEsMTU2LDcwLDEwNiwxMTIsNDAsMjM1LDY3LDAsMTQ1LDE5MiwxMzQsMjEwLDgxLDIwNSw0NCwxNSwyMCwyNDAsMTkzLDEzMyw0MiwxMTgsODksMTQ5LDk2LDIsMTksMTIzLDE5OCwxNTcsMTQxLDcyLDIyLDIwNCwyMjcsMjUwLDE1OCwxMzMsMjA0LDQ3LDU3LDkwLDExLDExNywxNzgsODksMSwxMTMsMjM5LDE0OCwxNiwyMTUsNDUsMTQ3LDE5Myw4NCw5NSwxNjgsMTExLDEyNiwyNSw5MiwyMzksMTU3LDExNCwyMTUsODAsMTI5LDE4OCwyMjIsMTIxLDE0NywxMDEsMjQyLDE4NCw1MywxMTAsMTEsMTAyLDczLDIzOSwyMjUsMTQzLDQ4LDE4OSwzOSwyMCwyNDEsOTIsMTgyLDE5OCwyMDgsMTUyLDE1MiwyMywxNDIsNTUsMjA0LDU3LDE0NCwxNTgsMjQxLDg5LDIyNSwyMzgsMjYsMzUsMjQwLDMyLDI1MCw2NCw5OCwyMDcsMzUsMjIsMjA4LDk2LDE3LDgxLDExMSwxMjYsOTIsNTQsMTc2LDIyOSwxMzQsMjIxLDIxNSw1Niw2NSwyNDMsMTUxLDE0NywxMjIsMjUxLDEzLDIwNCw0MiwyMzYsMjE5LDkyLDIsMCwwXQ%3D%3D)

Previously, using variables as slot names within loops was not possible because the slot object (specifically, the slot key) wasn't printed in the same location as the slotted elements.

This PR addresses this issue by refactoring the slot printing logic to ensure that the slot object is printed alongside the slotted elements when a dynamic slot name is used.

The other issues were fortuitously fixed with the refactor
 
## Testing

Added test cases covering each issue

## Docs

This wasn't possible before so we should probably document this. I'll make a docs PR

### CODE REVIEW

**Comment by MoustaphaDev** [comment]
!preview dynamic-slot-names

**Comment by MoustaphaDev** [comment]
!preview dynamic-slot-names

**Comment by MoustaphaDev** [comment]
!preview dynamic-slot-names

**Comment by MoustaphaDev** [comment]
!preview dynamic-slot-names

**Comment by MoustaphaDev** [comment]
!preview dynamic-slot-names

**Comment by MoustaphaDev** [comment]
!preview dynamic-slot-names

**Comment by MoustaphaDev** [comment]
!preview dynamic-slot-names

**Comment by MoustaphaDev** [comment]
!preview dynamic-slot-names

**Review by natemoo-re — APPROVED** [review]
Phenomenal work! Tests look great and the code makes sense.

My only open question is about the `mergeSlots` function in core because there might be projects with an older Astro runtime but this release of the compiler. If everything is backwards compatible that's great, otherwise we might need to figure out the best way to handle this migration.

**Review by matthewp — APPROVED** [review]

**Pull request merged**
