### PR TITLE
Fix lint error

### PR DESCRIPTION
**Pull request by natemoo-re**
## Changes

Update CI lint settings

## Testing

N/A

## Docs

N/A

### CODE REVIEW

**Review by Princesseuh — APPROVED** [review]

**Comment by jasikpark** [comment]
I'm confused, didn't the update to vert remove those values?

**Comment by natemoo-re** [comment]
> I'm confused, didn't the update to vert remove those values?

That would explain why we're getting a lint warning! But the actual code seems fine at runtime? I dunno what's happening.

**Comment by jasikpark** [comment]
hmm maybe I'm thinking of `js.Wrapper`?

https://github.com/norunners/vert/commit/106a353d42dd02e8824e44c471fe253633e1462e

**Comment by jasikpark** [comment]
see https://github.com/withastro/compiler/pull/644 for context

**Comment by jasikpark** [comment]
https://github.com/norunners/vert/blob/106a353d42dd02e8824e44c471fe253633e1462e/value.go#L18-L20 makes me think `vert.Value` should be defined..

**Comment by natemoo-re** [comment]
> hmm maybe I'm thinking of `js.Wrapper`?
> 
> [norunners/vert@106a353](https://github.com/norunners/vert/commit/106a353d42dd02e8824e44c471fe253633e1462e)

Yep, I think `js.Wrapper` is the thing that got removed. The `Vert` types have never been correct for some reason, so this is just a lint thing.

**Comment by jasikpark** [comment]
hmm ok

**Pull request merged**
