### PR TITLE
Update to go 1.19

### PR DESCRIPTION
**Pull request by jasikpark**
Needed for #619 

## Changes

- Upgrades Go to 1.19

## Testing

dep upgrade

## Docs

dep upgrade

### CODE REVIEW

**Comment by jasikpark** [comment]
https://github.com/golang/go/issues/50310 merh

**Comment by jasikpark** [comment]
gonna see if there's a https://github.com/norunners/vert 1.19 version ig?

**Comment by jasikpark** [comment]
okay, https://github.com/norunners/vert/pull/19 was merged, maybe @natemoo-re you can rebase your fork on it && we can upgrade natemoo-re/vert?

**Comment by natemoo-re** [comment]
Awesome, thanks @jasikpark! I'll take a look tomorrow!

**Comment by jasikpark** [comment]
hopefully there's not fundamental refactoring w/ how we use ValueOf 😅

**Comment by natemoo-re** [comment]
> 

Seems like we just needed to unwrap the value first!

**Review by natemoo-re — APPROVED** [review]
Looks great! Thanks for taking the lead on this ❤️

**Comment by jasikpark** [comment]
Had to get it in for my fuzzer #619 xD

**Review by jasikpark — COMMENTED** [review]
lgtm! glad i won't need to load a custom golang version for testing/building now

**Pull request merged**
