### PR TITLE
Fix quotations in pre-quoted attributes

### PR DESCRIPTION
**Pull request by ran-dall**
Fixes: #471

Special Thanks to @aFuzzyBear @okikio for their continued support and efforts.

Signed-off-by: Randall <ran.dall@icloud.com>

### CODE REVIEW

**Comment by matthewp** [comment]
Can you add a test?

**Comment by ran-dall** [comment]
@matthewp Np. However, I think we found some edge cases I'm still trying to wrap my head around.

**Comment by natemoo-re** [comment]
Thanks @ran-dall! Wanted to get this out in the next release. I took the liberty of cleaning up the tests. Appreciate you tackling this!

**Comment by ran-dall** [comment]
@natemoo-re NP. Be careful, though, because this one is the one that had the edge cases. I had some local commits to push to this PR that I intended to show you before it merged, but we can push them later or after we've had a chance to review my work (which we have still yet to do). I think I have to bring them all up-to-date `main` anyways now, cause a few things have been merged since I made tackled the issue board.

**Pull request merged**
