### PR TITLE
[wip] tinygo 0.21.0

### PR DESCRIPTION
**Pull request by drwpow**
## Changes

This PR just tracks if the next version of tinygo is working or not. If there’s a big ❌ at the bottom… you can take a wild guess

## Testing

No tests added.

## Docs

No docs

### CODE REVIEW

**Comment by natemoo-re** [comment]
👀 Hooray, new WASM bugs!

**Comment by drwpow** [comment]
> 👀 Hooray, new WASM bugs!

loool

**Comment by janimo** [comment]
0.21 only works if building with -gc leaking. The default conservative gc seems to have a regression and the .wasm file is also almost 300K larger than with 0.20.

**Comment by matthewp** [comment]
Looks like we're not going to be merging this for now. Thanks for the info @janimo, we'll keep an eye on improvements on the Go side, if you happen to find out that they've fixed these regressions please let us know if you can.

**Comment by aykevl** [comment]
> and the .wasm file is also almost 300K larger than with 0.20.

That's a significant increase!
I suspect this is because of [Asyncify](https://emscripten.org/docs/porting/asyncify.html) which we now use for concurrency (in short, the old method was subtly broken but that only became visible once we upgraded to LLVM 12). If you don't need concurrency, you can probably shrink the binary size a lot using `-scheduler=none`.

> 0.21 only works if building with -gc leaking. The default conservative gc seems to have a regression

Can you please make a small reproducer and report this upstream? We haven't seen any GC issues lately and I can't think of anything that would have broken GC - except if Asyncify somehow managed to confuse things.

**Comment by janimo** [comment]
@aykevl I remember trying with -scheduler=none, and while it resulted in a really small binary, it crashed regardless of the -gc option used. The only testcase I can think of is cloning this repo, make astro-wasm, npm install and npm run test which crashes. I didn't look deeper, sorry.

**Pull request closed without merging**
