### PR TITLE
Add regression test for #353

### PR DESCRIPTION
**Pull request by MoustaphaDev**
## Changes

#353 was seemingly fixed in #897. I added a regression test just in case.

## Testing

Added a printer test

## Docs

N/A bug fix

### CODE REVIEW

**Comment by natemoo-re** [comment]
@MoustaphaDev would you mind rebasing this? I tried locally but I'm not totally sure how the test needs to be updated.

**Comment by MoustaphaDev** [comment]
Sure I'll be back at my desk in a moment

**Comment by MoustaphaDev** [comment]
I suspect the tests failure to be caused by my PR in https://github.com/withastro/compiler/pull/930 that introduced changes to whitespaces in expressions. I'll investigate further

**Comment by MoustaphaDev** [comment]
Moving to a draft until tests are fixed

**Comment by MoustaphaDev** [comment]
Tests should pass after merging https://github.com/withastro/compiler/pull/932

**Review by natemoo-re — APPROVED** [review]

**Pull request merged**
